import { MigrationInterface, QueryRunner } from "typeorm";

export class init1675015780461 implements MigrationInterface {
    name = 'init1675015780461'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "crawl_site" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "created_on" TIMESTAMP NOT NULL, CONSTRAINT "PK_11f8436d3176ec17a3c0aff5937" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crawl_asset" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "asset_id" character varying NOT NULL, "site_id" integer NOT NULL, "title" character varying NOT NULL, "url" character varying NOT NULL, "preview_url" character varying NOT NULL, "tags" character varying NOT NULL, "asset_created_on" TIMESTAMP NOT NULL, "created_on" TIMESTAMP NOT NULL, "document_vectors" tsvector, CONSTRAINT "PK_5bb94da46d0bba3fe7ce47c2785" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_fts_doc_vec" ON "crawl_asset" ("document_vectors") `);
        await queryRunner.query(`ALTER TABLE "crawl_asset" ADD CONSTRAINT "FK_CrawlAsset_CrawlSite" FOREIGN KEY ("site_id") REFERENCES "crawl_site"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "crawl_asset" DROP CONSTRAINT "FK_CrawlAsset_CrawlSite"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fts_doc_vec"`);
        await queryRunner.query(`DROP TABLE "crawl_asset"`);
        await queryRunner.query(`DROP TABLE "crawl_site"`);
    }

}
